### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by gregberns** [splodingsocks/mochahq#8]
Just installed the project and opened it in my repo, but when I click on "All Tests" or "Location Helper" (the module under test), the server throws the following error.

Not sure what else would be helpful to provide.

```
MochaHQ serving on http://localhost:4042, from /Users/xxx/repos/MotionMobile/App
a user connected
a user connected
Got a pattern update: 
Running the test job
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn mocha ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

![image](https://cloud.githubusercontent.com/assets/1767458/23270991/0b4c6792-f9b3-11e6-9b6a-71a2dbe489ce.png)

**Comment by splodingsocks** [comment]
Hi, @gregburns! I'm so sorry I don't have the time to debug and fix right now. I just had a new daughter and started my Masters program alongside work, so I'm not sure that I'll be able to get to it any time soon. If you find out what's going on I'd be happy to merge a PR!

**Comment by gregberns** [comment]
No problem, if I have some time I'll take a look.

**Comment by splodingsocks** [comment]
Thanks!

**Comment by osvaldo-github** [comment]
Hi

This is an awesome tool.
I have the same problem. Anyone can help me solve this or suggest other tools like this?


Thanks for advance.

**Comment by splodingsocks** [comment]
Hi, @osvaldo-github!

I'm really sorry this isn't working for you. I changed jobs after writing this tool haven't used Mocha since then. I'm currently looking for a new maintainer. Hopefully if someone finds this useful they'll be able to step in and resolve this soon.

**Comment by NicholasThrom** [comment]
`npm install -g mocha` fixed this problem for me.
